environments:
  dev:
    paths:
      input: "data/input/employee_new.csv"
      clean_data: "data/output/dev/clean_data"
      transformed_data: "data/output/dev/transformed_data"
      aggregated_data: "data/output/dev/aggregated_data"
    logging_level: "DEBUG"
  prod:
    paths:
      input: "data/input/employee_new.csv"
      clean_data: "data/output/prod/clean_data"
      transformed_data: "data/output/prod/transformed_data"
      aggregated_data: "data/output/prod/aggregated_data"
    logging_level: "INFO"
