app_name: "PySpark S3 Example"
s3_source_path: "s3://emr-exercises-tg117/data/input/"
s3_destination_path: "s3://emr-exercises-tg117/data/output/"
input_format: "csv"
output_format: "parquet"
write_mode: "overwrite"
header: true
infer_schema: true
